import { Platform, StyleSheet } from 'react-native';

export const onboard = StyleSheet.create({
  wrapper: {
    flex: 1,
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingBottom: 50,
    paddingTop: 60,
  },
  welcomecontainer: {
    alignItems: 'center',
    paddingHorizontal: 20,
    borderWidth: 4,
    borderColor: '#008500',
    borderRadius: 14,
    backgroundColor: '#fff',
    paddingTop: 10,
    width: '90%',
    paddingBottom: 45,
  },
  welctitle: {
    fontSize: 24,
    color: '#002000',
    textAlign: 'center',
    fontFamily: 'Rufina-Bold',
  },
  welcsubtitle: {
    fontSize: 16,
    color: '#002000',
    marginTop: 10,
    textAlign: 'center',
    paddingHorizontal: 20,
    fontFamily: 'Rufina-Regular',
  },
  nextbutton: {
    bottom: 34,
  },
  agreeText: {
    fontSize: 16,
    color: '#002000',
    textAlign: 'center',
    fontFamily: 'Rufina-Regular',
  },
  checkBox: {
    width: 32,
    height: 32,
    borderWidth: 2,
    borderColor: '#002000',
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  nextgradientbutton: {
    width: 190,
    height: 61,
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
    top: -30,
    borderWidth: 1,
    borderColor: '#FF9900',
  },
  nextgradientbuttontext: {
    fontSize: 24,
    color: '#002000',
    fontFamily: 'Rufina-Bold',
    top: -2,
  },
  skipBtnText: {
    fontSize: 20,
    color: '#fff',
    fontFamily: 'Rufina-Bold',
  },
});

export const profile = StyleSheet.create({
  bg: {
    flex: 1,
    alignItems: 'center',
    paddingTop: 90,
    paddingBottom: 30,
  },
  topIconWrapper: { marginBottom: 20 },
  topIcon: { width: 90, height: 90, resizeMode: 'contain' },
  card: {
    width: '90%',
    borderWidth: 4,
    borderColor: '#008500',
    borderRadius: 18,
    paddingTop: 7,
    paddingBottom: 30,
    alignItems: 'center',
    backgroundColor: '#002000',
  },
  title: {
    fontSize: 24,
    color: '#FFFFFF',
    fontFamily: 'Rufina-Bold',
    marginBottom: 15,
  },
  photoBox: {
    width: 183,
    height: 183,
    borderRadius: 14,
    borderWidth: 4,
    borderColor: '#FFE400',
    overflow: 'hidden',
    marginTop: 8,
  },
  photo: { width: '100%', height: '100%' },
  photoPlaceholder: {
    flex: 1,
    backgroundColor: '#002000',
    justifyContent: 'flex-end',
    alignItems: 'center',
    paddingBottom: 14,
  },
  inputWrapper: {
    width: '90%',
    borderWidth: 4,
    borderColor: '#FFE400',
    borderRadius: 14,
    paddingHorizontal: 14,
    marginTop: 15,
  },
  input: {
    color: '#FFFFFF',
    paddingVertical: 10,
    fontSize: 16,
    fontFamily: 'Rufina-Bold',
    minHeight: 48,
  },
  textAreaWrapper: { height: 124, paddingVertical: 8 },
  textArea: { height: '100%', textAlignVertical: 'top' },
  button: {
    width: 190,
    height: 61,
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
  },
  buttonText: {
    fontSize: 22,
    color: '#002000',
    fontFamily: 'Rufina-Bold',
  },
});

export const chooseclub = StyleSheet.create({
  bg: {
    flex: 1,
    alignItems: 'center',
    paddingTop: 80,
    paddingBottom: 30,
  },
  logo: {
    width: 150,
    height: 150,
    resizeMode: 'contain',
    marginBottom: 20,
    borderRadius: 50,
  },
  card: {
    width: '90%',
    borderWidth: 4,
    borderColor: '#008500',
    borderRadius: 18,
    paddingVertical: 18,
    alignItems: 'center',
    backgroundColor: '#002000',
  },
  title: {
    fontSize: 22,
    color: '#FFFFFF',
    fontFamily: 'Rufina-Bold',
    marginBottom: 18,
  },
  row: {
    flexDirection: 'row',
    gap: 16,
  },
  clubBox: {
    width: 120,
    height: 120,
    borderRadius: 14,
    borderWidth: 4,
    borderColor: '#FFFFFF',
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
  },
  clubImg: {
    width: 90,
    height: 90,
    resizeMode: 'contain',
  },
  clubBtn: {
    marginTop: 6,
    backgroundColor: '#FFE400',
    borderRadius: 16,
    paddingVertical: 6,
    paddingHorizontal: 14,
    alignSelf: 'center',
  },
  clubBtnText: {
    fontSize: 14,
    color: '#002000',
    fontFamily: 'Rufina-Bold',
  },
  selectedBox: {
    width: 150,
    height: 150,
    borderRadius: 16,
    borderWidth: 4,
    borderColor: '#FFFFFF',
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 18,
  },
  selectedImg: {
    width: 110,
    height: 110,
    resizeMode: 'contain',
  },
  actionBtn: {
    width: 220,
    height: 60,
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  actionText: {
    fontSize: 20,
    color: '#002000',
    fontFamily: 'Rufina-Bold',
  },
  homeBtn: {
    width: 200,
    height: 62,
    borderRadius: 34,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 24,
  },
  homeText: {
    fontSize: 22,
    color: '#002000',
    fontFamily: 'Rufina-Bold',
  },
});

export const home = StyleSheet.create({
  bg: {
    flex: 1,
    paddingTop: 90,
    alignItems: 'center',
    paddingBottom: 30,
  },
  profileCard: {
    width: '90%',
    flexDirection: 'row',
    gap: 12,
    borderWidth: 4,
    borderColor: '#008500',
    borderRadius: 14,
    padding: 13,
    backgroundColor: '#002000',
    marginBottom: 20,
  },
  avatar: {
    width: 102,
    height: 102,
    borderRadius: 12,
    borderWidth: 3,
    borderColor: '#FFE400',
  },
  welcome: {
    fontSize: 20,
    color: '#FFE400',
    fontFamily: 'Rufina-Bold',
    width: '60%',
  },
  subTitle: {
    color: '#FFFFFF',
    fontFamily: 'Rufina-Bold',
    fontSize: 20,
    marginTop: 4,
  },
  motivationText: {
    color: '#FFFFFF',
    fontSize: 14,
    fontFamily: 'Rufina-Regular',
    marginTop: 3,
    width: '70%',
  },
  mainBtn: {
    width: 260,
    height: 61,
    borderRadius: 32,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 7,
    borderWidth: 1,
    borderColor: '#FF9900',
  },
  mainBtnText: {
    fontSize: 22,
    fontFamily: 'Rufina-Bold',
    color: '#002000',
  },
  dailyCard: {
    width: '90%',
    flexDirection: 'row',
    gap: 12,
    borderWidth: 4,
    borderColor: '#008500',
    borderRadius: 18,
    padding: 12,
    paddingBottom: 0,
    backgroundColor: '#002000',
    marginTop: 74,
  },
  dailyTitle: {
    color: '#FFFFFF',
    fontSize: 20,
    fontFamily: 'Rufina-Bold',
  },
  dailyText: {
    color: '#FFFFFF',
    fontSize: 14,
    marginTop: 6,
    fontFamily: 'Rufina-Regular',
  },
  timer: {
    position: 'absolute',
    right: 0,
    top: -16,
    backgroundColor: '#FFFFFF',
    paddingHorizontal: 8,
    height: 36,
    justifyContent: 'center',
    alignItems: 'center',
    borderRadius: 14,
    borderWidth: 4,
    borderColor: '#008500',
    flexDirection: 'row',
    gap: 4,
  },
  timerText: {
    fontSize: 12,
    color: '#002000',
    fontFamily: 'Rufina-Bold',
  },
});

export const task = StyleSheet.create({
  bg: {
    flex: 1,
    alignItems: 'center',
    paddingTop: 70,
  },
  introCard: {
    width: '90%',
    borderWidth: 4,
    borderColor: '#008500',
    borderRadius: 18,
    padding: 14,
    backgroundColor: '#002000',
    flexDirection: 'row',
    gap: 12,
    paddingBottom: 0,
  },
  introTitle: {
    fontSize: 22,
    color: '#FFFFFF',
    fontFamily: 'Rufina-Bold',
  },
  introText: {
    color: '#FFFFFF',
    fontSize: 14,
    marginTop: 6,
    fontFamily: 'Rufina-Regular',
  },
  startBtn: {
    width: 190,
    height: 61,
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 20,
    borderWidth: 1,
    borderColor: '#FF9900',
  },
  startText: {
    fontSize: 22,
    fontFamily: 'Rufina-Bold',
    color: '#002000',
  },
  clubTitle: {
    fontSize: 24,
    color: '#FFFFFF',
    fontFamily: 'Rufina-Bold',
    marginBottom: 10,
  },
  clubImageBox: {
    width: 108,
    height: 124,
    borderRadius: 14,
    borderWidth: 4,
    borderColor: '#008500',
    backgroundColor: '#FFFFFF',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 14,
    alignSelf: 'center',
  },
  clubImage: {
    width: 74,
    height: 89,
    resizeMode: 'contain',
  },
  card: {
    width: '90%',
    borderWidth: 4,
    borderColor: '#008500',
    borderRadius: 14,
    padding: 14,
    paddingBottom: 22,
    backgroundColor: '#FFFFFF',
  },
  cardTitle: {
    fontSize: 24,
    fontFamily: 'Rufina-Bold',
    color: '#002000',
    marginBottom: 12,
    textAlign: 'center',
  },
  taskRow: {
    flexDirection: 'row',
    marginVertical: 12,
    gap: 14,
    alignItems: 'center',
  },
  checkbox: {
    width: 32,
    height: 32,
    borderWidth: 2,
    borderColor: '#002000',
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  checked: {
    borderColor: '#008500',
  },
  taskText: {
    flex: 1,
    fontSize: 16,
    color: '#002000',
    fontFamily: 'Rufina-Regular',
  },
  doneBtn: {
    width: 190,
    height: 61,
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: -30,
    borderWidth: 1,
    borderColor: '#FF9900',
  },
  doneText: {
    color: '#FFFFFF',
    fontSize: 22,
    fontFamily: 'Rufina-Bold',
  },
  doneCard: {
    width: '90%',
    borderWidth: 4,
    borderColor: '#008500',
    borderRadius: 14,
    padding: 18,
    backgroundColor: '#002000',
    paddingBottom: 45,
    marginBottom: 30,
  },
  doneTitle: {
    fontSize: 24,
    color: '#FFFFFF',
    fontFamily: 'Rufina-Bold',
    marginBottom: 8,
    textAlign: 'center',
  },
  doneSubtitle: {
    color: '#FFFFFF',
    fontSize: 14,
    fontFamily: 'Rufina-Regular',
    marginBottom: 8,
    textAlign: 'center',
  },
  inputWrapper: {
    borderWidth: 4,
    borderColor: '#FFE400',
    borderRadius: 14,
    padding: 10,
    marginTop: 14,
    backgroundColor: '#002000',
  },
  input: {
    minHeight: 70,
    color: '#FFFFFF',
    fontFamily: 'Rufina-Bold',
    fontSize: 14,
  },
  photoBox: {
    width: 150,
    height: 150,
    borderWidth: 4,
    borderColor: '#FFE400',
    borderRadius: 14,
    justifyContent: 'flex-end',
    alignItems: 'center',
    marginTop: 18,
    backgroundColor: '#002000',
    alignSelf: 'center',
  },
  photo: {
    width: '100%',
    height: '100%',
    borderRadius: 14,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    position: 'absolute',
    bottom: -30,
    alignSelf: 'center',
    gap: 20,
    width: '100%',
  },
  saveBtn: {
    backgroundColor: '#00A000',
    paddingVertical: 14,
    paddingHorizontal: 32,
    borderRadius: 30,
  },
  saveText: {
    color: '#FFFFFF',
    fontFamily: 'Rufina-Bold',
    fontSize: 18,
  },
  shareBtn: {
    width: 124,
    height: 53,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#FF9900',
  },
  shareText: {
    color: '#FFFFFF',
    fontFamily: 'Rufina-Bold',
    fontSize: 18,
  },
  homeBtn: {
    width: 190,
    height: 61,
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 24,
    marginBottom: 50,
    borderWidth: 1,
    borderColor: '#FF9900',
  },
  homeText: {
    fontSize: 22,
    fontFamily: 'Rufina-Bold',
    color: '#002000',
  },
});

export const savednotes = StyleSheet.create({
  bg: {
    flex: 1,
    paddingTop: 70,
    alignItems: 'center',
    paddingBottom: 90,
  },
  shareBtn: {
    width: 124,
    height: 53,
    borderRadius: 30,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#FF9900',
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    position: 'absolute',
    bottom: -30,
    alignSelf: 'center',
    width: '95%',
  },
  headerCard: {
    width: '90%',
    borderWidth: 4,
    borderColor: '#008500',
    borderRadius: 18,
    padding: 14,
    backgroundColor: '#002000',
    flexDirection: 'row',
    gap: 12,
    marginBottom: 18,
    paddingBottom: 0,
  },
  headerTitle: {
    fontSize: 24,
    color: '#FFFFFF',
    fontFamily: 'Rufina-Bold',
  },
  headerText: {
    color: '#FFFFFF',
    fontSize: 14,
    marginTop: 4,
    fontFamily: 'Rufina-Regular',
  },
  doneText: {
    color: '#FFFFFF',
    fontSize: 22,
    fontFamily: 'Rufina-Bold',
  },
  emptyText: {
    color: '#FFFFFF',
    fontSize: 20,
    marginTop: 40,
    fontFamily: 'Rufina-Regular',
  },
  noteCard: {
    width: '90%',
    borderWidth: 4,
    borderColor: '#008500',
    borderRadius: 18,
    padding: 14,
    backgroundColor: '#002000',
    flexDirection: 'row',
    gap: 12,
    marginBottom: 46,
    paddingBottom: 50,
    justifyContent: 'center',
  },
  noteImage: {
    width: 150,
    height: 150,
    borderRadius: 14,
    borderWidth: 3,
    borderColor: '#FFE400',
  },
  noteDate: {
    color: '#FFFFFF',
    fontSize: 22,
    fontFamily: 'Rufina-Bold',
  },
  noteText: {
    color: '#FFFFFF',
    fontSize: 14,
    marginTop: 8,
    fontFamily: 'Rufina-Bold',
  },
  noteActions: {
    flexDirection: 'row',
    gap: 12,
    marginTop: 10,
  },
  deleteBtn: {
    backgroundColor: '#A00000',
    paddingVertical: 10,
    paddingHorizontal: 22,
    borderRadius: 30,
  },
  deleteText: {
    color: '#FFFFFF',
    fontFamily: 'Rufina-Bold',
  },
  shareText: {
    color: '#FFFFFF',
    fontFamily: 'Rufina-Bold',
  },
  homeBtn: {
    backgroundColor: '#FFE400',
    width: 190,
    height: 61,
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 20,
    borderWidth: 1,
    borderColor: '#FF9900',
  },
  homeText: {
    fontSize: 22,
    fontFamily: 'Rufina-Bold',
    color: '#002000',
  },
  modalBg: {
    flex: 1,
    backgroundColor: Platform.OS === 'ios' ? 'transparent' : '#00000086',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalCard: {
    width: '85%',
    borderWidth: 4,
    borderColor: '#008500',
    borderRadius: 18,
    padding: 18,
    backgroundColor: '#002000',
    alignItems: 'center',
    flexDirection: 'row',
    paddingBottom: 0,
    gap: 15,
    bottom: 50,
  },
  modalTitle: {
    fontSize: 22,
    color: '#FFFFFF',
    fontFamily: 'Rufina-Bold',
  },
  modalText: {
    color: '#FFFFFF',
    fontSize: 14,
    marginVertical: 10,
    textAlign: 'center',
    fontFamily: 'Rufina-Regular',
  },
  modalRow: {
    flexDirection: 'row',
    gap: 16,
    marginTop: 10,
  },
  modalDeleteBtn: {
    backgroundColor: '#A00000',
    paddingVertical: 12,
    paddingHorizontal: 28,
    borderRadius: 30,
  },
  modalDeleteText: {
    color: '#FFFFFF',
    fontFamily: 'Rufina-Bold',
    fontSize: 16,
  },
  modalCancelBtn: {
    backgroundColor: '#00A000',
    paddingVertical: 12,
    paddingHorizontal: 28,
    borderRadius: 30,
  },
  modalCancelText: {
    color: '#FFFFFF',
    fontFamily: 'Rufina-Bold',
    fontSize: 16,
  },
});

export const settings = StyleSheet.create({
  bg: {
    flex: 1,
    paddingTop: 50,
    alignItems: 'center',
  },
  introCard: {
    width: '90%',
    borderWidth: 4,
    borderColor: '#008500',
    borderRadius: 18,
    padding: 14,
    backgroundColor: '#002000',
    flexDirection: 'row',
    gap: 12,
    marginBottom: 18,
    paddingBottom: 0,
  },
  introTitle: {
    fontSize: 22,
    color: '#FFFFFF',
    fontFamily: 'Rufina-Bold',
  },
  introText: {
    color: '#FFFFFF',
    fontSize: 14,
    marginTop: 6,
    fontFamily: 'Rufina-Regular',
  },
  switchBg: {
    width: 35,
    height: 16,
    backgroundColor: '#E50000',
    borderRadius: 7,
    justifyContent: 'center',
    padding: 2,
    paddingHorizontal: 2,
  },
  profileCard: {
    width: '90%',
    borderWidth: 4,
    borderColor: '#008500',
    borderRadius: 18,
    padding: 16,
    backgroundColor: '#002000',
    alignItems: 'center',
    paddingBottom: 30,
  },
  profileTitle: {
    fontSize: 22,
    color: '#FFFFFF',
    fontFamily: 'Rufina-Bold',
    marginBottom: 12,
  },
  photoBox: {
    width: 160,
    height: 160,
    borderRadius: 18,
    borderWidth: 4,
    borderColor: '#FFE400',
    overflow: 'hidden',
    marginBottom: 14,
  },
  photo: {
    width: '100%',
    height: '100%',
  },
  photoIcon: {
    position: 'absolute',
    bottom: 10,
    alignSelf: 'center',
  },
  profileField: {
    width: '90%',
    borderWidth: 4,
    borderColor: '#FFE400',
    borderRadius: 14,
    padding: 10,
    marginBottom: 10,
  },
  profileText: {
    color: '#FFFFFF',
    fontSize: 16,
    fontFamily: 'Rufina-Bold',
    textAlign: 'center',
  },
  changeBtn: {
    width: 290,
    height: 60,
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
    top: -30,
  },
  changeText: {
    fontSize: 20,
    color: '#002000',
    fontFamily: 'Rufina-Bold',
  },
  section: {
    width: '90%',
    borderWidth: 4,
    borderColor: '#008500',
    borderRadius: 14,
    padding: 12,
    backgroundColor: '#002000',
    marginBottom: 16,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  sectionText: {
    color: '#FFFFFF',
    fontSize: 24,
    fontFamily: 'Rufina-Bold',
  },
  resetBtn: {
    height: 60,
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 14,
    borderWidth: 1,
    borderColor: '#FF9900',
  },
  resetText: {
    color: '#FFFFFF',
    fontSize: 20,
    fontFamily: 'Rufina-Bold',
  },
  homeBtn: {
    width: 190,
    height: 61,
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 30,
    borderWidth: 1,
    borderColor: '#FF9900',
  },
  homeText: {
    fontSize: 22,
    fontFamily: 'Rufina-Bold',
    color: '#002000',
  },
});

export const about = StyleSheet.create({
  bg: {
    flex: 1,
    paddingTop: 70,
    alignItems: 'center',
    paddingBottom: 30,
  },
  headerCard: {
    width: '90%',
    borderWidth: 4,
    borderColor: '#008500',
    borderRadius: 18,
    padding: 14,
    backgroundColor: '#002000',
    flexDirection: 'row',
    gap: 12,
    marginBottom: 18,
    paddingBottom: 0,
  },
  headerImg: {
    width: 60,
    height: 60,
    borderRadius: 12,
  },
  headerTitle: {
    fontSize: 24,
    color: '#FFFFFF',
    fontFamily: 'Rufina-Bold',
  },
  headerText: {
    color: '#FFFFFF',
    fontSize: 14,
    marginTop: 4,
    fontFamily: 'Rufina-Regular',
  },
  aboutCard: {
    width: '90%',
    borderWidth: 4,
    borderColor: '#008500',
    borderRadius: 18,
    padding: 18,
    paddingBottom: 0,
    backgroundColor: '#002000',
    alignItems: 'center',
  },
  logo: {
    width: 160,
    height: 160,
    resizeMode: 'contain',
    marginBottom: 20,
    borderRadius: 42,
  },
  aboutText: {
    color: '#FFFFFF',
    fontSize: 14,
    lineHeight: 18,
    textAlign: 'center',
    fontFamily: 'Rufina-Regular',
  },
  shareBtn: {
    width: 124,
    height: 53,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#FF9900',
    top: 26,
  },
  shareText: {
    color: '#FFFFFF',
    fontSize: 22,
    fontFamily: 'Rufina-Bold',
  },
  homeBtn: {
    width: 190,
    height: 61,
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#FF9900',
    marginTop: 65,
  },
  homeText: {
    fontSize: 22,
    fontFamily: 'Rufina-Bold',
    color: '#002000',
  },
});

export const editprofile = StyleSheet.create({
  bg: {
    flex: 1,
    alignItems: 'center',
    paddingTop: 90,
    paddingBottom: 30,
  },
  card: {
    width: '90%',
    borderWidth: 4,
    borderColor: '#008500',
    borderRadius: 18,
    padding: 16,
    backgroundColor: '#002000',
    alignItems: 'center',
    paddingBottom: 40,
  },
  title: {
    fontSize: 24,
    color: '#FFFFFF',
    fontFamily: 'Rufina-Bold',
    marginBottom: 14,
  },
  photoBox: {
    width: 170,
    height: 170,
    borderRadius: 18,
    borderWidth: 4,
    borderColor: '#FFE400',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 14,
    overflow: 'hidden',
  },
  photo: {
    width: '100%',
    height: '100%',
  },
  photoIcon: {
    position: 'absolute',
    bottom: 10,
  },
  inputWrapper: {
    width: '90%',
    borderWidth: 4,
    borderColor: '#FFE400',
    borderRadius: 14,
    paddingHorizontal: 14,
    marginTop: 12,
    paddingVertical: 8,
  },
  textAreaWrapper: {
    height: 90,
    paddingVertical: 10,
  },
  input: {
    color: '#FFF',
    fontSize: 16,
    fontFamily: 'Rufina-Bold',
  },
  textArea: {
    height: '100%',
    textAlignVertical: 'top',
  },
  row: {
    flexDirection: 'row',
    gap: 14,
    marginTop: 18,
  },
  cancelBtn: {
    width: 130,
    height: 56,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  changeBtn: {
    width: 130,
    height: 56,
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    borderWidth: 1,
    borderColor: '#FF9900',
  },
  btnText: {
    color: '#FFFFFF',
    fontSize: 18,
    fontFamily: 'Rufina-Bold',
  },
  changeText: {
    color: '#fff',
    fontSize: 18,
    fontFamily: 'Rufina-Bold',
  },
  homeBtn: {
    width: 190,
    height: 61,
    borderRadius: 32,
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 10,
    borderWidth: 1,
    borderColor: '#FF9900',
  },
  homeText: {
    fontSize: 22,
    fontFamily: 'Rufina-Bold',
    color: '#002000',
  },
});
